paritytech/frame-metadata

.github/workflows/rust.yml, frame-metadata/Cargo.toml, frame-metadata/src/lib.rs, frame-metadata/src/v12.rs, frame-metadata/src/v13.rs
Adds a `v13` feature which includes `scale-info` type information.
The `v13` metadata is still a work in progress and will likely require some further iteration as I work on the integration process with substrate.
=> Integrate scale-info for type generation

frame-metadata/Cargo.toml, frame-metadata/src/lib.rs, frame-metadata/src/v12.rs, frame-metadata/src/v13.rs
More features for substrate compatibility and for use of the resulting encoded metadata in https://github.com/ascjones/chameleon.
- Support SCALE decoding of v13 metadata
- Support serde serialization of v13 metadata
- Add definintion for extrinsics and their signed extensions
=> Complete v13 type definitions, support metadata decoding and serde

frame-metadata/src/lib.rs, frame-metadata/src/v12.rs, frame-metadata/src/v13.rs
Currently this type is duplicated in both `v12` and `v13`, when it should be version agnostic because it contains the `RuntimeMetadataPrefixed` enum. 
I've left the `META_RESERVED` constant in both versions, even though it is the same, in case it can change in the future.
=> Extract duplicated RuntimeMetadataPrefixed struct to crate level

frame-metadata/Cargo.toml, frame-metadata/src/lib.rs, frame-metadata/src/v12.rs, frame-metadata/src/v13.rs
Convert to use new `decode` feature in `scale-info` for environments where decoding is enabled, which removes the hacky string parameterization. See https://github.com/paritytech/scale-info/pull/59
=> Update to latest scale-info & codec, remove string parameterization

frame-metadata/src/v13.rs
Also corrects `storage` to be a single object instead of a `Vec`
=> Change `StorageEntryType` keys/values to types instead of strings

frame-metadata/src/v13.rs
Change v13 constants from an Option a plain Vec. It was a mistakenly translated from v12 as an Option
=> Fix up v13 constants metadata

frame-metadata/src/v13.rs
It's made redundant by the type information provided by `scale-info`
=> Remove `FunctionArgumentMetadata::is_compact` flag

frame-metadata/src/v13.rs
Replace custom definitions for errors and event metadata with scale-info type information for the pallet `Event` and `Error` types (depends on https://github.com/paritytech/scale-info/pull/87 which adds documentation to the `scale-info` derive). 
As @thiolliere [pointed out](https://github.com/paritytech/substrate/pull/8615#discussion_r613292720), metadata for events and errors (which are expanded to simple enums) can be captured already by the `scale_info` derives. 
Call definitions could also just use the `scale-info` derives on the `Call` enum also, but we will keep the custom types in case we need to add additional metadata, see the [comment below](https://github.com/paritytech/frame-metadata/pull/11#issuecomment-827556297).
Also: 
- Renames types/comments with module -> pallet
- Adds …
=> Refactor v13 metadata types

.github/workflows/rust.yml, frame-metadata/Cargo.toml, frame-metadata/src/decode_different.rs, frame-metadata/src/lib.rs, frame-metadata/src/v12.rs, frame-metadata/src/v13.rs, frame-metadata/src/v14.rs
New `v13` just been introduced in https://github.com/paritytech/substrate/pull/8635 so we need move the new `scale-info` stuff to `v14` and add the Storage `NMap` variant.
=> Copy v13 metadata from substrate, move new scale-info version to v14

frame-metadata/src/lib.rs
In order that the user doesn't need to fully qualify the path including the version to the types, when using the latest available version.
So when `v15` comes along we just update the reexport to that.
=> Reexport all the types from the latest version

frame-metadata/src/v14.rs
Adds the type of `SignedExtension::AdditionalSigned` to the `SignedExtensionMetadata`.
For @jacogr  as part of https://github.com/polkadot-js/api/pull/3759
=> Add `additional_signed` field for `SignedExtension` payload data

frame-metadata/src/lib.rs
Plucked from https://github.com/paritytech/frame-metadata/pull/24/files#diff-361abe92f6544eac70ee0471d4128328b07f6991bc01d7cc70fe919c55077ff4R116
Just becasue it's something that would be handy for us in desub land :)
Not sure how far off that draft PR is; feel free to close this if it's not too far off anyway!
=> Add function to return version from metadata

frame-metadata/src/decode_different.rs, frame-metadata/src/lib.rs, frame-metadata/src/v10.rs, frame-metadata/src/v11.rs, frame-metadata/src/v12.rs, frame-metadata/src/v13.rs, frame-metadata/src/v14.rs, frame-metadata/src/v8.rs, frame-metadata/src/v9.rs
Also enables warnings for missing docs.
Follow up PRs should document v8 –> v12 and remove the `allow(missing_docs)` attribute on those modules.﻿
=> Document all v14, v13 and most of v8 items

.github/dependabot.yml, .github/workflows/deny.yml, .github/workflows/lint.yml, .github/workflows/rust.yml
In order to improve our security posture with GitHub Actions usage. I've made a version pinning ether to commit hash or to specific version.
Additionally added `dependabot` to track GHA version changes.
Related issues and policy:
https://github.com/paritytech/ci_cd/issues/114
https://github.com/paritytech/ci_cd/issues/464
https://github.com/paritytech/ci_cd/wiki/Policies-and-regulations:-GitHub-Actions-usage-policies
=> Pin GHA versions and add dependabot

.github/workflows/rust.yml, frame-metadata/Cargo.toml, frame-metadata/src/lib.rs, frame-metadata/src/v10.rs, frame-metadata/src/v11.rs, frame-metadata/src/v12.rs, frame-metadata/src/v14.rs, frame-metadata/src/v8.rs, frame-metadata/src/v9.rs
This PR is proposing upstreaming the work done by Integritee parachain and in particular @echevrier to make frame-metadata work for no_std. I have been using this fork myself for a month or two now and can confirm it works fine in browsers.
It's pretty important that we have no_std support as otherwise it's a big blocker for anyone trying to decode scale in wasm (ie. in the browser).
Happy to implement any feedback to get no_std support into main.
Co-authored-by: echevrier <edith.chevrier@scs.ch>
=> add no_std support

.github/workflows/rust.yml, frame-metadata/src/lib.rs
This PR re-enables the github CI that was not running due to
```bash
Invalid workflow file: .github/workflows/rust.yml#L74
The workflow is not valid. .github/workflows/rust.yml (Line: 74, Col: 9): 'uses' is already defined .github/workflows/rust.yml (Line: 81, Col: 9): 'uses' is already defined
```
While at it, add some extra checks for documentation, style and tests. 
// CC: @paritytech/tools-team
=> chore: Enable rust tests in CI

frame-metadata/Cargo.toml, frame-metadata/src/decode_different.rs, frame-metadata/src/lib.rs, frame-metadata/src/v10.rs, frame-metadata/src/v11.rs, frame-metadata/src/v12.rs, frame-metadata/src/v14.rs, frame-metadata/src/v15.rs, frame-metadata/src/v8.rs, frame-metadata/src/v9.rs
The v15 metadata extends the v14 with the `runtime` field. This field (similarly to the `pallets` field) contains all the information needed to generate an API in higher-level projects (subxt, capi etc).
The runtime field is a collection of `TraitMetadata` objects that contain: 
- trait name
- optionally a trait version
- methods available:
- method name
- method inputs (name and meta::Type - ie `bytes: &[u8]`)
- method output (meta::Type)
- documentation
- documentation (that is only visible at `decl_runtime_apis` and valuable for UX)
While the metadata v15 might not yet be in its final form, this PR focus on adding support for the Runtime while allowing users (Substrate) to still utilize the v14.
The metadata v15 also includes the documentation of pallets needed by …
=> Add metadata V15 with Runtime API support

frame-metadata/src/v15.rs
This PR adds the outer enum types to the metadata:
- RuntimeCall enum type
- RuntimeEvent enum type
- RuntimeError enum type
For more info visit: https://github.com/paritytech/substrate/pull/14143
// CC @paritytech/subxt-team
=> Metadata V15: Add outer enum types for calls, events, errors

frame-metadata/src/v15.rs
This PR renames the `error_enum_ty` to better reflect the type details.
Considering that it does not represent the `DispatchError` emitted by the chain,
it contains only the information needed to decode the `ModuleError` of the
`DispatchError::Module` variant.
The [ModuleError](https://docs.rs/sp-runtime/24.0.0/sp_runtime/struct.ModuleError.html) is represented by a raw form in sp-runtime:
```rust
pub struct ModuleError {
pub index: [u8](https://doc.rust-lang.org/nightly/std/primitive.u8.html),
pub error: [[u8](https://doc.rust-lang.org/nightly/std/primitive.u8.html); [4](https://doc.rust-lang.org/nightly/std/primitive.array.html)],
pub message: [Option](https://doc.rust-lang.org/nightly/core/option/enum.Option.html)<&'static [str](https://doc.rust-lang.org/nightly/std/primitive.str.html)> …
```
=> v15: Rename `error_enum_ty` to `module_error_enum_ty`

frame-metadata/src/v15.rs
This PR adds custom values to the metadata.
While at it, introduce `OuterEnums` to group the outer enums.
For more details see: https://github.com/paritytech/substrate/issues/12939#issuecomment-1572254731.
// @paritytech/subxt-team
=> V15: Add custom values to the metadata

frame-metadata/src/v15.rs
Metadata is enriched to provide users with additional types for decoding extrinsics:
- Address type
- Call type
- Signature type
- Extra type
For more info visit: https://github.com/paritytech/substrate/pull/14123
// CC @paritytech/subxt-team
=> Metadata V15: Enrich extrinsic type info for decoding

frame-metadata/src/lib.rs
This PR places the metadata V15 under the "current" feature flag marking the stabilization.
@paritytech/subxt-team
=> Stabilize V15 metadata

frame-metadata/src/lib.rs, frame-metadata/src/v16.rs
This PR adds the metadata V16 to the frame-metadata crate, under the `unstable` feature flag.
The u32 ID of the metadata V16 is currently `u32::MAX` to mark the metadata as unstable.
This PR paves the way towards collecting the metadata in substrate and enables the extraction of the metadata via the runtime API calls. 
=> v16: Add unstable metadata v16

CHANGELOG.md, frame-metadata/Cargo.toml
- v16: Add unstable metadata v16 [#82](https://github.com/paritytech/frame-metadata/pull/82)
=> chore: Release v17 with v16 unstable metadata

frame-metadata/src/v16.rs
This PR adds the following to the v16 metadata:
- remove `ExtrinsicMetadata::call_ty` as it can be found in the other enums field of the metadata
- remove `ExtrinsicMetadata::extra_ty` as it can be found in the tx extensions
- rename `TransactionExtensionMetadata::additional_signed` to `TransactionExtensionMetadata::implicit`
- add `TransactionExtensionMetadata::version` u8 for versioning extensions 
=> v16: ExtrinsicMetadata extensions

CHANGELOG.md, frame-metadata/Cargo.toml
- v16: ExtrinsicMetadata extensions [#86](https://github.com/paritytech/frame-metadata/pull/86)
=> chore: Release v18.0.0 with unstable v16 `ExtrinsicMetadata` extensions

frame-metadata/src/v16.rs
This PR adds the pallet view functions into the metadata v16.
Part of:
- https://github.com/paritytech/polkadot-sdk/issues/6833
=> v16: Add view functions to the pallets metadata

frame-metadata/src/lib.rs, frame-metadata/src/v16.rs
This solves https://github.com/paritytech/polkadot-sdk/issues/7352 on the `frame-metadata` side and it will be completed by https://github.com/paritytech/polkadot-sdk/pull/7607 on the runtime side.
=> Add Runtime Api version to v16

CHANGELOG.md, frame-metadata/Cargo.toml
Metadata version 16 is currently unstable and can be enabled using the unstable feature flag.
- Add Runtime Api version to v16 [#92](https://github.com/paritytech/frame-metadata/pull/92)
cc @paritytech/subxt-team @re-gius
=> chore: Release frame-metadata v20.0.0

frame-metadata/Cargo.toml, frame-metadata/src/v16.rs
Address some niggles in the V16 format; a couple of `Compact`s to reduce the size a little, and sharing more types for easier from/into conversions in other crates.
Closes #94 
Closes #95 
Closes #96
=> Address V16 pre-stabilization niggles

CHANGELOG.md, frame-metadata/Cargo.toml
- Address some small niggles in the unstable V16 metadata [#98](https://github.com/paritytech/frame-metadata/pull/98)
=> Prepare to release 21.0.0

frame-metadata/src/v16.rs
`call_ty` is useful to build an extrinsic. Theoretically, one should be able to encode and decode extrinsics with just the `ExtrinsicMetadata` and the `Registry`, and without it it can't be done. It was readded, keeping it as in metadata v15.
Other changes:
- Moved `deprecation_info` down in runtime APIS to maintain consistency with all other fields.
- `id` was moved up in view functions, to make the codec of the view function just `<id>|<runtime API>`.
- The variant-deprecation enum now uses the same indices as in regular deprecation to maintain consistency and allow decoding with the same codec.
=> fix: add back `call_ty` and reorder some fields

CHANGELOG.md, frame-metadata/Cargo.toml, frame-metadata/src/lib.rs
This release stabilizes metadata V16, moving it from being marked as "unstable" and hidden behind that feature flag, to being "current" and having version 16 rather than `u32::MAX`.
=> Prepare to stabilize V16 metadata and release v23.0.0
